- name: Add the GitLab package repository
  shell: "curl -L 'https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh' | sudo bash"

- name: install packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - gitlab-runner
    state: present

- name: add gitlab-runner to docker group
  ansible.builtin.user:
    name: gitlab-runner
    groups: docker

- name: ensure runner is started and enabled at boot
  ansible.builtin.systemd:
    name: gitlab-runner
    state: started
    enabled: yes

# - name: Register gitlab shell runner
#   command: |
#     gitlab-runner register \
#     --non-interactive \
#     --url "https://gitlab.com/" \
#     --registration-token "{{ reg_token }}" \
#     --executor "shell" \
#     --description "shell executor" \
#     --tag-list "azure, shell, ansible" \
#     --run-untagged="false" \
#     --locked="true" \
#     --access-level="ref_protected"
