- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: install packages
  ansible.builtin.apt:
    name:
      - git
      - htop
      - iotop
      - lm-sensors
      - smartmontools
      - python3-pip
    state: present
