- name: Install mysqldump
  ansible.builtin.apt:
    name:
      - mysql-client
    state: present
    update_cache: true
    allow_unauthenticated: true

- name: Install aws cli with pip
  ansible.builtin.pip:
    name:
      - awscli

- name: ~/.aws directory
  ansible.builtin.file:
    path: ~/.aws
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Copy aws credentials
  ansible.builtin.copy:
    src: files/credentials
    dest: ~/.aws/credentials
    owner: root
    group: root
    mode: '644'

- name: Backup script
  ansible.builtin.copy:
    src: files/db_backup.sh
    dest: /root/scripts/db_backup.sh
    owner: root
    group: root
    mode: '700'

- name: Sync script
  ansible.builtin.copy:
    src: files/db_sync.sh
    dest: /root/scripts/db_sync.sh
    owner: root
    group: root
    mode: '700'

- name: Add backup to crontab
  ansible.builtin.cron:
    name: mysql dump all databases
    minute: "01"
    hour: "3"
    user: root
    job: "/root/scripts/db_backup.sh > /dev/null 2>&1"

- name: Add sync to crontab
  ansible.builtin.cron:
    name: sync backups with s3 storage
    minute: "20"
    hour: "3"
    user: root
    job: "/root/scripts/db_sync.sh > /dev/null 2>&1"
