- name: Download mc
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: ~/s3/mc
    mode: '0755'

- name: Set minio alias
  ansible.builtin.command: ~/s3/mc alias set {{ ALIAS }} {{ S3_ENDPOINT }} {{ ACCESS_KEY }} {{ SECRET_KEY }}
  changed_when: true

- name: Install mysqldump
  ansible.builtin.apt:
    name:
      - mysql-client
    state: present
    update_cache: true
    allow_unauthenticated: true

- name: Backup script
  ansible.builtin.copy:
    src: files/db_backup.sh
    dest: /root/scripts/db_backup.sh
    owner: root
    group: root
    mode: '700'

- name: Sync script
  ansible.builtin.copy:
    src: files/db_sync.sh
    dest: /root/scripts/db_sync.sh
    owner: root
    group: root
    mode: '700'

- name: Add backup to crontab
  ansible.builtin.cron:
    name: mysql dump all databases
    minute: "01"
    hour: "3"
    user: root
    job: "/root/scripts/db_backup.sh > /dev/null 2>&1"
